<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <StartupObject>Phanmemwar3.Program</StartupObject>
    <AssemblyName>WarcraftPlatformManager</AssemblyName>
    <RootNamespace>Phanmemwar3</RootNamespace>
    <ApplicationIcon>WarcraftPlatformManager.ico</ApplicationIcon>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource Include="lang.ini" />
    <EmbeddedResource Include="WarcraftPlatformManager.ico" />
    <None Update="lang.ini;settings.ini;WarcraftPlatformManager.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
